################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../application/ucgui/WM/WM.c \
../application/ucgui/WM/WMMemDev.c \
../application/ucgui/WM/WMTouch.c \
../application/ucgui/WM/WM_AttachWindow.c \
../application/ucgui/WM/WM_BringToBottom.c \
../application/ucgui/WM/WM_BringToTop.c \
../application/ucgui/WM/WM_Broadcast.c \
../application/ucgui/WM/WM_CheckScrollPos.c \
../application/ucgui/WM/WM_CriticalHandle.c \
../application/ucgui/WM/WM_DIAG.c \
../application/ucgui/WM/WM_EnableWindow.c \
../application/ucgui/WM/WM_ForEachDesc.c \
../application/ucgui/WM/WM_GetBkColor.c \
../application/ucgui/WM/WM_GetClientRect.c \
../application/ucgui/WM/WM_GetClientWindow.c \
../application/ucgui/WM/WM_GetDesktopWindow.c \
../application/ucgui/WM/WM_GetDesktopWindowEx.c \
../application/ucgui/WM/WM_GetDiagInfo.c \
../application/ucgui/WM/WM_GetDialogItem.c \
../application/ucgui/WM/WM_GetFirstChild.c \
../application/ucgui/WM/WM_GetFlags.c \
../application/ucgui/WM/WM_GetFocussedWindow.c \
../application/ucgui/WM/WM_GetId.c \
../application/ucgui/WM/WM_GetInsideRect.c \
../application/ucgui/WM/WM_GetInsideRectExScrollbar.c \
../application/ucgui/WM/WM_GetInvalidRect.c \
../application/ucgui/WM/WM_GetNextSibling.c \
../application/ucgui/WM/WM_GetOrg.c \
../application/ucgui/WM/WM_GetParent.c \
../application/ucgui/WM/WM_GetPrevSibling.c \
../application/ucgui/WM/WM_GetScrollPartner.c \
../application/ucgui/WM/WM_GetScrollState.c \
../application/ucgui/WM/WM_GetScrollbar.c \
../application/ucgui/WM/WM_GetWindowRect.c \
../application/ucgui/WM/WM_GetWindowSize.c \
../application/ucgui/WM/WM_HasCaptured.c \
../application/ucgui/WM/WM_HasFocus.c \
../application/ucgui/WM/WM_Hide.c \
../application/ucgui/WM/WM_IsCompletelyVisible.c \
../application/ucgui/WM/WM_IsEnabled.c \
../application/ucgui/WM/WM_IsFocussable.c \
../application/ucgui/WM/WM_IsVisible.c \
../application/ucgui/WM/WM_IsWindow.c \
../application/ucgui/WM/WM_MakeModal.c \
../application/ucgui/WM/WM_Move.c \
../application/ucgui/WM/WM_MoveChildTo.c \
../application/ucgui/WM/WM_NotifyParent.c \
../application/ucgui/WM/WM_OnKey.c \
../application/ucgui/WM/WM_PID__GetPrevState.c \
../application/ucgui/WM/WM_Paint.c \
../application/ucgui/WM/WM_ResizeWindow.c \
../application/ucgui/WM/WM_Screen2Win.c \
../application/ucgui/WM/WM_SendMessageNoPara.c \
../application/ucgui/WM/WM_SendToParent.c \
../application/ucgui/WM/WM_SetAnchor.c \
../application/ucgui/WM/WM_SetCallback.c \
../application/ucgui/WM/WM_SetCapture.c \
../application/ucgui/WM/WM_SetCaptureMove.c \
../application/ucgui/WM/WM_SetCreateFlags.c \
../application/ucgui/WM/WM_SetDesktopColor.c \
../application/ucgui/WM/WM_SetFocus.c \
../application/ucgui/WM/WM_SetFocusOnNextChild.c \
../application/ucgui/WM/WM_SetFocusOnPrevChild.c \
../application/ucgui/WM/WM_SetId.c \
../application/ucgui/WM/WM_SetScrollState.c \
../application/ucgui/WM/WM_SetScrollbar.c \
../application/ucgui/WM/WM_SetSize.c \
../application/ucgui/WM/WM_SetTrans.c \
../application/ucgui/WM/WM_SetTransState.c \
../application/ucgui/WM/WM_SetUserClipRect.c \
../application/ucgui/WM/WM_SetXSize.c \
../application/ucgui/WM/WM_SetYSize.c \
../application/ucgui/WM/WM_SetpfPollPID.c \
../application/ucgui/WM/WM_Show.c \
../application/ucgui/WM/WM_StayOnTop.c \
../application/ucgui/WM/WM_Timer.c \
../application/ucgui/WM/WM_TimerExternal.c \
../application/ucgui/WM/WM_UserData.c \
../application/ucgui/WM/WM_Validate.c \
../application/ucgui/WM/WM_ValidateWindow.c \
../application/ucgui/WM/WM__ForEachDesc.c \
../application/ucgui/WM/WM__GetFirstSibling.c \
../application/ucgui/WM/WM__GetFocussedChild.c \
../application/ucgui/WM/WM__GetLastSibling.c \
../application/ucgui/WM/WM__GetOrg_AA.c \
../application/ucgui/WM/WM__GetPrevSibling.c \
../application/ucgui/WM/WM__IsAncestor.c \
../application/ucgui/WM/WM__IsChild.c \
../application/ucgui/WM/WM__IsEnabled.c \
../application/ucgui/WM/WM__NotifyVisChanged.c \
../application/ucgui/WM/WM__Screen2Client.c \
../application/ucgui/WM/WM__SendMessage.c \
../application/ucgui/WM/WM__SendMessageIfEnabled.c \
../application/ucgui/WM/WM__SendMessageNoPara.c \
../application/ucgui/WM/WM__UpdateChildPositions.c 

OBJS += \
./application/ucgui/WM/WM.o \
./application/ucgui/WM/WMMemDev.o \
./application/ucgui/WM/WMTouch.o \
./application/ucgui/WM/WM_AttachWindow.o \
./application/ucgui/WM/WM_BringToBottom.o \
./application/ucgui/WM/WM_BringToTop.o \
./application/ucgui/WM/WM_Broadcast.o \
./application/ucgui/WM/WM_CheckScrollPos.o \
./application/ucgui/WM/WM_CriticalHandle.o \
./application/ucgui/WM/WM_DIAG.o \
./application/ucgui/WM/WM_EnableWindow.o \
./application/ucgui/WM/WM_ForEachDesc.o \
./application/ucgui/WM/WM_GetBkColor.o \
./application/ucgui/WM/WM_GetClientRect.o \
./application/ucgui/WM/WM_GetClientWindow.o \
./application/ucgui/WM/WM_GetDesktopWindow.o \
./application/ucgui/WM/WM_GetDesktopWindowEx.o \
./application/ucgui/WM/WM_GetDiagInfo.o \
./application/ucgui/WM/WM_GetDialogItem.o \
./application/ucgui/WM/WM_GetFirstChild.o \
./application/ucgui/WM/WM_GetFlags.o \
./application/ucgui/WM/WM_GetFocussedWindow.o \
./application/ucgui/WM/WM_GetId.o \
./application/ucgui/WM/WM_GetInsideRect.o \
./application/ucgui/WM/WM_GetInsideRectExScrollbar.o \
./application/ucgui/WM/WM_GetInvalidRect.o \
./application/ucgui/WM/WM_GetNextSibling.o \
./application/ucgui/WM/WM_GetOrg.o \
./application/ucgui/WM/WM_GetParent.o \
./application/ucgui/WM/WM_GetPrevSibling.o \
./application/ucgui/WM/WM_GetScrollPartner.o \
./application/ucgui/WM/WM_GetScrollState.o \
./application/ucgui/WM/WM_GetScrollbar.o \
./application/ucgui/WM/WM_GetWindowRect.o \
./application/ucgui/WM/WM_GetWindowSize.o \
./application/ucgui/WM/WM_HasCaptured.o \
./application/ucgui/WM/WM_HasFocus.o \
./application/ucgui/WM/WM_Hide.o \
./application/ucgui/WM/WM_IsCompletelyVisible.o \
./application/ucgui/WM/WM_IsEnabled.o \
./application/ucgui/WM/WM_IsFocussable.o \
./application/ucgui/WM/WM_IsVisible.o \
./application/ucgui/WM/WM_IsWindow.o \
./application/ucgui/WM/WM_MakeModal.o \
./application/ucgui/WM/WM_Move.o \
./application/ucgui/WM/WM_MoveChildTo.o \
./application/ucgui/WM/WM_NotifyParent.o \
./application/ucgui/WM/WM_OnKey.o \
./application/ucgui/WM/WM_PID__GetPrevState.o \
./application/ucgui/WM/WM_Paint.o \
./application/ucgui/WM/WM_ResizeWindow.o \
./application/ucgui/WM/WM_Screen2Win.o \
./application/ucgui/WM/WM_SendMessageNoPara.o \
./application/ucgui/WM/WM_SendToParent.o \
./application/ucgui/WM/WM_SetAnchor.o \
./application/ucgui/WM/WM_SetCallback.o \
./application/ucgui/WM/WM_SetCapture.o \
./application/ucgui/WM/WM_SetCaptureMove.o \
./application/ucgui/WM/WM_SetCreateFlags.o \
./application/ucgui/WM/WM_SetDesktopColor.o \
./application/ucgui/WM/WM_SetFocus.o \
./application/ucgui/WM/WM_SetFocusOnNextChild.o \
./application/ucgui/WM/WM_SetFocusOnPrevChild.o \
./application/ucgui/WM/WM_SetId.o \
./application/ucgui/WM/WM_SetScrollState.o \
./application/ucgui/WM/WM_SetScrollbar.o \
./application/ucgui/WM/WM_SetSize.o \
./application/ucgui/WM/WM_SetTrans.o \
./application/ucgui/WM/WM_SetTransState.o \
./application/ucgui/WM/WM_SetUserClipRect.o \
./application/ucgui/WM/WM_SetXSize.o \
./application/ucgui/WM/WM_SetYSize.o \
./application/ucgui/WM/WM_SetpfPollPID.o \
./application/ucgui/WM/WM_Show.o \
./application/ucgui/WM/WM_StayOnTop.o \
./application/ucgui/WM/WM_Timer.o \
./application/ucgui/WM/WM_TimerExternal.o \
./application/ucgui/WM/WM_UserData.o \
./application/ucgui/WM/WM_Validate.o \
./application/ucgui/WM/WM_ValidateWindow.o \
./application/ucgui/WM/WM__ForEachDesc.o \
./application/ucgui/WM/WM__GetFirstSibling.o \
./application/ucgui/WM/WM__GetFocussedChild.o \
./application/ucgui/WM/WM__GetLastSibling.o \
./application/ucgui/WM/WM__GetOrg_AA.o \
./application/ucgui/WM/WM__GetPrevSibling.o \
./application/ucgui/WM/WM__IsAncestor.o \
./application/ucgui/WM/WM__IsChild.o \
./application/ucgui/WM/WM__IsEnabled.o \
./application/ucgui/WM/WM__NotifyVisChanged.o \
./application/ucgui/WM/WM__Screen2Client.o \
./application/ucgui/WM/WM__SendMessage.o \
./application/ucgui/WM/WM__SendMessageIfEnabled.o \
./application/ucgui/WM/WM__SendMessageNoPara.o \
./application/ucgui/WM/WM__UpdateChildPositions.o 

C_DEPS += \
./application/ucgui/WM/WM.d \
./application/ucgui/WM/WMMemDev.d \
./application/ucgui/WM/WMTouch.d \
./application/ucgui/WM/WM_AttachWindow.d \
./application/ucgui/WM/WM_BringToBottom.d \
./application/ucgui/WM/WM_BringToTop.d \
./application/ucgui/WM/WM_Broadcast.d \
./application/ucgui/WM/WM_CheckScrollPos.d \
./application/ucgui/WM/WM_CriticalHandle.d \
./application/ucgui/WM/WM_DIAG.d \
./application/ucgui/WM/WM_EnableWindow.d \
./application/ucgui/WM/WM_ForEachDesc.d \
./application/ucgui/WM/WM_GetBkColor.d \
./application/ucgui/WM/WM_GetClientRect.d \
./application/ucgui/WM/WM_GetClientWindow.d \
./application/ucgui/WM/WM_GetDesktopWindow.d \
./application/ucgui/WM/WM_GetDesktopWindowEx.d \
./application/ucgui/WM/WM_GetDiagInfo.d \
./application/ucgui/WM/WM_GetDialogItem.d \
./application/ucgui/WM/WM_GetFirstChild.d \
./application/ucgui/WM/WM_GetFlags.d \
./application/ucgui/WM/WM_GetFocussedWindow.d \
./application/ucgui/WM/WM_GetId.d \
./application/ucgui/WM/WM_GetInsideRect.d \
./application/ucgui/WM/WM_GetInsideRectExScrollbar.d \
./application/ucgui/WM/WM_GetInvalidRect.d \
./application/ucgui/WM/WM_GetNextSibling.d \
./application/ucgui/WM/WM_GetOrg.d \
./application/ucgui/WM/WM_GetParent.d \
./application/ucgui/WM/WM_GetPrevSibling.d \
./application/ucgui/WM/WM_GetScrollPartner.d \
./application/ucgui/WM/WM_GetScrollState.d \
./application/ucgui/WM/WM_GetScrollbar.d \
./application/ucgui/WM/WM_GetWindowRect.d \
./application/ucgui/WM/WM_GetWindowSize.d \
./application/ucgui/WM/WM_HasCaptured.d \
./application/ucgui/WM/WM_HasFocus.d \
./application/ucgui/WM/WM_Hide.d \
./application/ucgui/WM/WM_IsCompletelyVisible.d \
./application/ucgui/WM/WM_IsEnabled.d \
./application/ucgui/WM/WM_IsFocussable.d \
./application/ucgui/WM/WM_IsVisible.d \
./application/ucgui/WM/WM_IsWindow.d \
./application/ucgui/WM/WM_MakeModal.d \
./application/ucgui/WM/WM_Move.d \
./application/ucgui/WM/WM_MoveChildTo.d \
./application/ucgui/WM/WM_NotifyParent.d \
./application/ucgui/WM/WM_OnKey.d \
./application/ucgui/WM/WM_PID__GetPrevState.d \
./application/ucgui/WM/WM_Paint.d \
./application/ucgui/WM/WM_ResizeWindow.d \
./application/ucgui/WM/WM_Screen2Win.d \
./application/ucgui/WM/WM_SendMessageNoPara.d \
./application/ucgui/WM/WM_SendToParent.d \
./application/ucgui/WM/WM_SetAnchor.d \
./application/ucgui/WM/WM_SetCallback.d \
./application/ucgui/WM/WM_SetCapture.d \
./application/ucgui/WM/WM_SetCaptureMove.d \
./application/ucgui/WM/WM_SetCreateFlags.d \
./application/ucgui/WM/WM_SetDesktopColor.d \
./application/ucgui/WM/WM_SetFocus.d \
./application/ucgui/WM/WM_SetFocusOnNextChild.d \
./application/ucgui/WM/WM_SetFocusOnPrevChild.d \
./application/ucgui/WM/WM_SetId.d \
./application/ucgui/WM/WM_SetScrollState.d \
./application/ucgui/WM/WM_SetScrollbar.d \
./application/ucgui/WM/WM_SetSize.d \
./application/ucgui/WM/WM_SetTrans.d \
./application/ucgui/WM/WM_SetTransState.d \
./application/ucgui/WM/WM_SetUserClipRect.d \
./application/ucgui/WM/WM_SetXSize.d \
./application/ucgui/WM/WM_SetYSize.d \
./application/ucgui/WM/WM_SetpfPollPID.d \
./application/ucgui/WM/WM_Show.d \
./application/ucgui/WM/WM_StayOnTop.d \
./application/ucgui/WM/WM_Timer.d \
./application/ucgui/WM/WM_TimerExternal.d \
./application/ucgui/WM/WM_UserData.d \
./application/ucgui/WM/WM_Validate.d \
./application/ucgui/WM/WM_ValidateWindow.d \
./application/ucgui/WM/WM__ForEachDesc.d \
./application/ucgui/WM/WM__GetFirstSibling.d \
./application/ucgui/WM/WM__GetFocussedChild.d \
./application/ucgui/WM/WM__GetLastSibling.d \
./application/ucgui/WM/WM__GetOrg_AA.d \
./application/ucgui/WM/WM__GetPrevSibling.d \
./application/ucgui/WM/WM__IsAncestor.d \
./application/ucgui/WM/WM__IsChild.d \
./application/ucgui/WM/WM__IsEnabled.d \
./application/ucgui/WM/WM__NotifyVisChanged.d \
./application/ucgui/WM/WM__Screen2Client.d \
./application/ucgui/WM/WM__SendMessage.d \
./application/ucgui/WM/WM__SendMessageIfEnabled.d \
./application/ucgui/WM/WM__SendMessageNoPara.d \
./application/ucgui/WM/WM__UpdateChildPositions.d 


# Each subdirectory must supply rules for building sources it contributes
application/ucgui/WM/%.o: ../application/ucgui/WM/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imac -mabi=ilp32 -mcmodel=medany -mno-save-restore -O0 -ffunction-sections -fdata-sections -fno-common  -g -DDOWNLOAD_MODE=DOWNLOAD_MODE_FLASHXIP -I"D:\risc_studio\456\nuclei_sdk\NMSIS\DSP\Include" -I"D:\risc_studio\456\nuclei_sdk\NMSIS\NN\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Board\gd32vf103v_rvstar\Include" -I"D:\risc_studio\456\application" -I"D:\risc_studio\456\nuclei_sdk\NMSIS\Core\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Common\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Common\Include\Usb" -I"D:\risc_studio\456\application\ucgui" -I"D:\risc_studio\456\application\ucgui\WM" -I"D:\risc_studio\456\application\ucgui\ConvertColor" -I"D:\risc_studio\456\application\ucgui\ConvertMono" -I"D:\risc_studio\456\application\ucgui\Core" -I"D:\risc_studio\456\application\ucgui\Font" -I"D:\risc_studio\456\application\ucgui\JPEG" -I"D:\risc_studio\456\application\ucgui\LCDDriver" -I"D:\risc_studio\456\application\ucgui\MemDev" -I"D:\risc_studio\456\application\ucgui\MultiLayer" -I"D:\risc_studio\456\application\ucgui\Widget" -I"D:\risc_studio\456\application\gui_config" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


