################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../application/ucgui/Widget/BUTTON.c \
../application/ucgui/Widget/BUTTON_BMP.c \
../application/ucgui/Widget/BUTTON_Bitmap.c \
../application/ucgui/Widget/BUTTON_Create.c \
../application/ucgui/Widget/BUTTON_CreateIndirect.c \
../application/ucgui/Widget/BUTTON_Default.c \
../application/ucgui/Widget/BUTTON_Get.c \
../application/ucgui/Widget/BUTTON_IsPressed.c \
../application/ucgui/Widget/BUTTON_SelfDraw.c \
../application/ucgui/Widget/BUTTON_SetTextAlign.c \
../application/ucgui/Widget/BUTTON_StreamedBitmap.c \
../application/ucgui/Widget/BUTTON__SetBitmapObj.c \
../application/ucgui/Widget/CHECKBOX.c \
../application/ucgui/Widget/CHECKBOX_Create.c \
../application/ucgui/Widget/CHECKBOX_CreateIndirect.c \
../application/ucgui/Widget/CHECKBOX_Default.c \
../application/ucgui/Widget/CHECKBOX_GetState.c \
../application/ucgui/Widget/CHECKBOX_Image.c \
../application/ucgui/Widget/CHECKBOX_IsChecked.c \
../application/ucgui/Widget/CHECKBOX_SetBkColor.c \
../application/ucgui/Widget/CHECKBOX_SetDefaultImage.c \
../application/ucgui/Widget/CHECKBOX_SetFont.c \
../application/ucgui/Widget/CHECKBOX_SetImage.c \
../application/ucgui/Widget/CHECKBOX_SetNumStates.c \
../application/ucgui/Widget/CHECKBOX_SetSpacing.c \
../application/ucgui/Widget/CHECKBOX_SetState.c \
../application/ucgui/Widget/CHECKBOX_SetText.c \
../application/ucgui/Widget/CHECKBOX_SetTextAlign.c \
../application/ucgui/Widget/CHECKBOX_SetTextColor.c \
../application/ucgui/Widget/DIALOG.c \
../application/ucgui/Widget/DROPDOWN.c \
../application/ucgui/Widget/DROPDOWN_Create.c \
../application/ucgui/Widget/DROPDOWN_CreateIndirect.c \
../application/ucgui/Widget/DROPDOWN_DeleteItem.c \
../application/ucgui/Widget/DROPDOWN_InsertString.c \
../application/ucgui/Widget/DROPDOWN_ItemSpacing.c \
../application/ucgui/Widget/DROPDOWN_SetAutoScroll.c \
../application/ucgui/Widget/DROPDOWN_SetTextAlign.c \
../application/ucgui/Widget/DROPDOWN_SetTextHeight.c \
../application/ucgui/Widget/EDIT.c \
../application/ucgui/Widget/EDITBin.c \
../application/ucgui/Widget/EDITDec.c \
../application/ucgui/Widget/EDITFloat.c \
../application/ucgui/Widget/EDITHex.c \
../application/ucgui/Widget/EDIT_Create.c \
../application/ucgui/Widget/EDIT_CreateIndirect.c \
../application/ucgui/Widget/EDIT_Default.c \
../application/ucgui/Widget/EDIT_GetNumChars.c \
../application/ucgui/Widget/EDIT_SetCursorAtChar.c \
../application/ucgui/Widget/EDIT_SetInsertMode.c \
../application/ucgui/Widget/EDIT_SetSel.c \
../application/ucgui/Widget/EDIT_SetpfAddKeyEx.c \
../application/ucgui/Widget/EDIT_SetpfUpdateBuffer.c \
../application/ucgui/Widget/FRAMEWIN.c \
../application/ucgui/Widget/FRAMEWIN_AddMenu.c \
../application/ucgui/Widget/FRAMEWIN_Button.c \
../application/ucgui/Widget/FRAMEWIN_ButtonClose.c \
../application/ucgui/Widget/FRAMEWIN_ButtonMax.c \
../application/ucgui/Widget/FRAMEWIN_ButtonMin.c \
../application/ucgui/Widget/FRAMEWIN_Create.c \
../application/ucgui/Widget/FRAMEWIN_CreateIndirect.c \
../application/ucgui/Widget/FRAMEWIN_Default.c \
../application/ucgui/Widget/FRAMEWIN_Get.c \
../application/ucgui/Widget/FRAMEWIN_IsMinMax.c \
../application/ucgui/Widget/FRAMEWIN_MinMaxRest.c \
../application/ucgui/Widget/FRAMEWIN_SetBorderSize.c \
../application/ucgui/Widget/FRAMEWIN_SetColors.c \
../application/ucgui/Widget/FRAMEWIN_SetFont.c \
../application/ucgui/Widget/FRAMEWIN_SetResizeable.c \
../application/ucgui/Widget/FRAMEWIN_SetTitleHeight.c \
../application/ucgui/Widget/FRAMEWIN_SetTitleVis.c \
../application/ucgui/Widget/FRAMEWIN__UpdateButtons.c \
../application/ucgui/Widget/GUI_ARRAY.c \
../application/ucgui/Widget/GUI_ARRAY_DeleteItem.c \
../application/ucgui/Widget/GUI_ARRAY_InsertItem.c \
../application/ucgui/Widget/GUI_ARRAY_ResizeItem.c \
../application/ucgui/Widget/GUI_DRAW.c \
../application/ucgui/Widget/GUI_DRAW_BITMAP.c \
../application/ucgui/Widget/GUI_DRAW_BMP.c \
../application/ucgui/Widget/GUI_DRAW_STREAMED.c \
../application/ucgui/Widget/GUI_DRAW_Self.c \
../application/ucgui/Widget/GUI_EditBin.c \
../application/ucgui/Widget/GUI_EditDec.c \
../application/ucgui/Widget/GUI_EditFloat.c \
../application/ucgui/Widget/GUI_EditHex.c \
../application/ucgui/Widget/GUI_EditString.c \
../application/ucgui/Widget/GUI_HOOK.c \
../application/ucgui/Widget/HEADER.c \
../application/ucgui/Widget/HEADER_BMP.c \
../application/ucgui/Widget/HEADER_Bitmap.c \
../application/ucgui/Widget/HEADER_Create.c \
../application/ucgui/Widget/HEADER_CreateIndirect.c \
../application/ucgui/Widget/HEADER_StreamedBitmap.c \
../application/ucgui/Widget/HEADER__SetDrawObj.c \
../application/ucgui/Widget/LISTBOX.c \
../application/ucgui/Widget/LISTBOX_Create.c \
../application/ucgui/Widget/LISTBOX_CreateIndirect.c \
../application/ucgui/Widget/LISTBOX_Default.c \
../application/ucgui/Widget/LISTBOX_DeleteItem.c \
../application/ucgui/Widget/LISTBOX_Font.c \
../application/ucgui/Widget/LISTBOX_GetItemText.c \
../application/ucgui/Widget/LISTBOX_GetNumItems.c \
../application/ucgui/Widget/LISTBOX_InsertString.c \
../application/ucgui/Widget/LISTBOX_ItemDisabled.c \
../application/ucgui/Widget/LISTBOX_ItemSpacing.c \
../application/ucgui/Widget/LISTBOX_MultiSel.c \
../application/ucgui/Widget/LISTBOX_ScrollStep.c \
../application/ucgui/Widget/LISTBOX_SetAutoScroll.c \
../application/ucgui/Widget/LISTBOX_SetBkColor.c \
../application/ucgui/Widget/LISTBOX_SetOwner.c \
../application/ucgui/Widget/LISTBOX_SetOwnerDraw.c \
../application/ucgui/Widget/LISTBOX_SetScrollbarWidth.c \
../application/ucgui/Widget/LISTBOX_SetString.c \
../application/ucgui/Widget/LISTBOX_SetTextColor.c \
../application/ucgui/Widget/LISTVIEW.c \
../application/ucgui/Widget/LISTVIEW_Create.c \
../application/ucgui/Widget/LISTVIEW_CreateIndirect.c \
../application/ucgui/Widget/LISTVIEW_Default.c \
../application/ucgui/Widget/LISTVIEW_DeleteColumn.c \
../application/ucgui/Widget/LISTVIEW_DeleteRow.c \
../application/ucgui/Widget/LISTVIEW_GetBkColor.c \
../application/ucgui/Widget/LISTVIEW_GetFont.c \
../application/ucgui/Widget/LISTVIEW_GetHeader.c \
../application/ucgui/Widget/LISTVIEW_GetNumColumns.c \
../application/ucgui/Widget/LISTVIEW_GetNumRows.c \
../application/ucgui/Widget/LISTVIEW_GetSel.c \
../application/ucgui/Widget/LISTVIEW_GetTextColor.c \
../application/ucgui/Widget/LISTVIEW_SetBkColor.c \
../application/ucgui/Widget/LISTVIEW_SetColumnWidth.c \
../application/ucgui/Widget/LISTVIEW_SetFont.c \
../application/ucgui/Widget/LISTVIEW_SetGridVis.c \
../application/ucgui/Widget/LISTVIEW_SetItemColor.c \
../application/ucgui/Widget/LISTVIEW_SetItemText.c \
../application/ucgui/Widget/LISTVIEW_SetLBorder.c \
../application/ucgui/Widget/LISTVIEW_SetRBorder.c \
../application/ucgui/Widget/LISTVIEW_SetRowHeight.c \
../application/ucgui/Widget/LISTVIEW_SetSel.c \
../application/ucgui/Widget/LISTVIEW_SetTextAlign.c \
../application/ucgui/Widget/LISTVIEW_SetTextColor.c \
../application/ucgui/Widget/MENU.c \
../application/ucgui/Widget/MENU_Attach.c \
../application/ucgui/Widget/MENU_CreateIndirect.c \
../application/ucgui/Widget/MENU_Default.c \
../application/ucgui/Widget/MENU_DeleteItem.c \
../application/ucgui/Widget/MENU_DisableItem.c \
../application/ucgui/Widget/MENU_EnableItem.c \
../application/ucgui/Widget/MENU_GetItem.c \
../application/ucgui/Widget/MENU_GetItemText.c \
../application/ucgui/Widget/MENU_GetNumItems.c \
../application/ucgui/Widget/MENU_InsertItem.c \
../application/ucgui/Widget/MENU_Popup.c \
../application/ucgui/Widget/MENU_SetBkColor.c \
../application/ucgui/Widget/MENU_SetBorderSize.c \
../application/ucgui/Widget/MENU_SetFont.c \
../application/ucgui/Widget/MENU_SetItem.c \
../application/ucgui/Widget/MENU_SetTextColor.c \
../application/ucgui/Widget/MENU__FindItem.c \
../application/ucgui/Widget/MESSAGEBOX.c \
../application/ucgui/Widget/MULTIEDIT.c \
../application/ucgui/Widget/MULTIEDIT_Create.c \
../application/ucgui/Widget/MULTIEDIT_CreateIndirect.c \
../application/ucgui/Widget/MULTIPAGE.c \
../application/ucgui/Widget/MULTIPAGE_Create.c \
../application/ucgui/Widget/MULTIPAGE_CreateIndirect.c \
../application/ucgui/Widget/MULTIPAGE_Default.c \
../application/ucgui/Widget/PROGBAR.c \
../application/ucgui/Widget/PROGBAR_Create.c \
../application/ucgui/Widget/PROGBAR_CreateIndirect.c \
../application/ucgui/Widget/RADIO.c \
../application/ucgui/Widget/RADIO_Create.c \
../application/ucgui/Widget/RADIO_CreateIndirect.c \
../application/ucgui/Widget/RADIO_Default.c \
../application/ucgui/Widget/RADIO_Image.c \
../application/ucgui/Widget/RADIO_SetBkColor.c \
../application/ucgui/Widget/RADIO_SetDefaultImage.c \
../application/ucgui/Widget/RADIO_SetFont.c \
../application/ucgui/Widget/RADIO_SetGroupId.c \
../application/ucgui/Widget/RADIO_SetImage.c \
../application/ucgui/Widget/RADIO_SetText.c \
../application/ucgui/Widget/RADIO_SetTextColor.c \
../application/ucgui/Widget/SCROLLBAR.c \
../application/ucgui/Widget/SCROLLBAR_Create.c \
../application/ucgui/Widget/SCROLLBAR_CreateIndirect.c \
../application/ucgui/Widget/SCROLLBAR_Defaults.c \
../application/ucgui/Widget/SCROLLBAR_GetValue.c \
../application/ucgui/Widget/SCROLLBAR_SetWidth.c \
../application/ucgui/Widget/SLIDER.c \
../application/ucgui/Widget/SLIDER_Create.c \
../application/ucgui/Widget/SLIDER_CreateIndirect.c \
../application/ucgui/Widget/TEXT.c \
../application/ucgui/Widget/TEXT_Create.c \
../application/ucgui/Widget/TEXT_CreateIndirect.c \
../application/ucgui/Widget/TEXT_SetBkColor.c \
../application/ucgui/Widget/TEXT_SetFont.c \
../application/ucgui/Widget/TEXT_SetText.c \
../application/ucgui/Widget/TEXT_SetTextAlign.c \
../application/ucgui/Widget/TEXT_SetTextColor.c \
../application/ucgui/Widget/WIDGET.c \
../application/ucgui/Widget/WIDGET_Effect_3D.c \
../application/ucgui/Widget/WIDGET_Effect_3D1L.c \
../application/ucgui/Widget/WIDGET_Effect_3D2L.c \
../application/ucgui/Widget/WIDGET_Effect_None.c \
../application/ucgui/Widget/WIDGET_Effect_Simple.c \
../application/ucgui/Widget/WIDGET_FillStringInRect.c \
../application/ucgui/Widget/WIDGET_SetEffect.c \
../application/ucgui/Widget/WIDGET_SetWidth.c \
../application/ucgui/Widget/WINDOW.c \
../application/ucgui/Widget/WINDOW_Default.c 

OBJS += \
./application/ucgui/Widget/BUTTON.o \
./application/ucgui/Widget/BUTTON_BMP.o \
./application/ucgui/Widget/BUTTON_Bitmap.o \
./application/ucgui/Widget/BUTTON_Create.o \
./application/ucgui/Widget/BUTTON_CreateIndirect.o \
./application/ucgui/Widget/BUTTON_Default.o \
./application/ucgui/Widget/BUTTON_Get.o \
./application/ucgui/Widget/BUTTON_IsPressed.o \
./application/ucgui/Widget/BUTTON_SelfDraw.o \
./application/ucgui/Widget/BUTTON_SetTextAlign.o \
./application/ucgui/Widget/BUTTON_StreamedBitmap.o \
./application/ucgui/Widget/BUTTON__SetBitmapObj.o \
./application/ucgui/Widget/CHECKBOX.o \
./application/ucgui/Widget/CHECKBOX_Create.o \
./application/ucgui/Widget/CHECKBOX_CreateIndirect.o \
./application/ucgui/Widget/CHECKBOX_Default.o \
./application/ucgui/Widget/CHECKBOX_GetState.o \
./application/ucgui/Widget/CHECKBOX_Image.o \
./application/ucgui/Widget/CHECKBOX_IsChecked.o \
./application/ucgui/Widget/CHECKBOX_SetBkColor.o \
./application/ucgui/Widget/CHECKBOX_SetDefaultImage.o \
./application/ucgui/Widget/CHECKBOX_SetFont.o \
./application/ucgui/Widget/CHECKBOX_SetImage.o \
./application/ucgui/Widget/CHECKBOX_SetNumStates.o \
./application/ucgui/Widget/CHECKBOX_SetSpacing.o \
./application/ucgui/Widget/CHECKBOX_SetState.o \
./application/ucgui/Widget/CHECKBOX_SetText.o \
./application/ucgui/Widget/CHECKBOX_SetTextAlign.o \
./application/ucgui/Widget/CHECKBOX_SetTextColor.o \
./application/ucgui/Widget/DIALOG.o \
./application/ucgui/Widget/DROPDOWN.o \
./application/ucgui/Widget/DROPDOWN_Create.o \
./application/ucgui/Widget/DROPDOWN_CreateIndirect.o \
./application/ucgui/Widget/DROPDOWN_DeleteItem.o \
./application/ucgui/Widget/DROPDOWN_InsertString.o \
./application/ucgui/Widget/DROPDOWN_ItemSpacing.o \
./application/ucgui/Widget/DROPDOWN_SetAutoScroll.o \
./application/ucgui/Widget/DROPDOWN_SetTextAlign.o \
./application/ucgui/Widget/DROPDOWN_SetTextHeight.o \
./application/ucgui/Widget/EDIT.o \
./application/ucgui/Widget/EDITBin.o \
./application/ucgui/Widget/EDITDec.o \
./application/ucgui/Widget/EDITFloat.o \
./application/ucgui/Widget/EDITHex.o \
./application/ucgui/Widget/EDIT_Create.o \
./application/ucgui/Widget/EDIT_CreateIndirect.o \
./application/ucgui/Widget/EDIT_Default.o \
./application/ucgui/Widget/EDIT_GetNumChars.o \
./application/ucgui/Widget/EDIT_SetCursorAtChar.o \
./application/ucgui/Widget/EDIT_SetInsertMode.o \
./application/ucgui/Widget/EDIT_SetSel.o \
./application/ucgui/Widget/EDIT_SetpfAddKeyEx.o \
./application/ucgui/Widget/EDIT_SetpfUpdateBuffer.o \
./application/ucgui/Widget/FRAMEWIN.o \
./application/ucgui/Widget/FRAMEWIN_AddMenu.o \
./application/ucgui/Widget/FRAMEWIN_Button.o \
./application/ucgui/Widget/FRAMEWIN_ButtonClose.o \
./application/ucgui/Widget/FRAMEWIN_ButtonMax.o \
./application/ucgui/Widget/FRAMEWIN_ButtonMin.o \
./application/ucgui/Widget/FRAMEWIN_Create.o \
./application/ucgui/Widget/FRAMEWIN_CreateIndirect.o \
./application/ucgui/Widget/FRAMEWIN_Default.o \
./application/ucgui/Widget/FRAMEWIN_Get.o \
./application/ucgui/Widget/FRAMEWIN_IsMinMax.o \
./application/ucgui/Widget/FRAMEWIN_MinMaxRest.o \
./application/ucgui/Widget/FRAMEWIN_SetBorderSize.o \
./application/ucgui/Widget/FRAMEWIN_SetColors.o \
./application/ucgui/Widget/FRAMEWIN_SetFont.o \
./application/ucgui/Widget/FRAMEWIN_SetResizeable.o \
./application/ucgui/Widget/FRAMEWIN_SetTitleHeight.o \
./application/ucgui/Widget/FRAMEWIN_SetTitleVis.o \
./application/ucgui/Widget/FRAMEWIN__UpdateButtons.o \
./application/ucgui/Widget/GUI_ARRAY.o \
./application/ucgui/Widget/GUI_ARRAY_DeleteItem.o \
./application/ucgui/Widget/GUI_ARRAY_InsertItem.o \
./application/ucgui/Widget/GUI_ARRAY_ResizeItem.o \
./application/ucgui/Widget/GUI_DRAW.o \
./application/ucgui/Widget/GUI_DRAW_BITMAP.o \
./application/ucgui/Widget/GUI_DRAW_BMP.o \
./application/ucgui/Widget/GUI_DRAW_STREAMED.o \
./application/ucgui/Widget/GUI_DRAW_Self.o \
./application/ucgui/Widget/GUI_EditBin.o \
./application/ucgui/Widget/GUI_EditDec.o \
./application/ucgui/Widget/GUI_EditFloat.o \
./application/ucgui/Widget/GUI_EditHex.o \
./application/ucgui/Widget/GUI_EditString.o \
./application/ucgui/Widget/GUI_HOOK.o \
./application/ucgui/Widget/HEADER.o \
./application/ucgui/Widget/HEADER_BMP.o \
./application/ucgui/Widget/HEADER_Bitmap.o \
./application/ucgui/Widget/HEADER_Create.o \
./application/ucgui/Widget/HEADER_CreateIndirect.o \
./application/ucgui/Widget/HEADER_StreamedBitmap.o \
./application/ucgui/Widget/HEADER__SetDrawObj.o \
./application/ucgui/Widget/LISTBOX.o \
./application/ucgui/Widget/LISTBOX_Create.o \
./application/ucgui/Widget/LISTBOX_CreateIndirect.o \
./application/ucgui/Widget/LISTBOX_Default.o \
./application/ucgui/Widget/LISTBOX_DeleteItem.o \
./application/ucgui/Widget/LISTBOX_Font.o \
./application/ucgui/Widget/LISTBOX_GetItemText.o \
./application/ucgui/Widget/LISTBOX_GetNumItems.o \
./application/ucgui/Widget/LISTBOX_InsertString.o \
./application/ucgui/Widget/LISTBOX_ItemDisabled.o \
./application/ucgui/Widget/LISTBOX_ItemSpacing.o \
./application/ucgui/Widget/LISTBOX_MultiSel.o \
./application/ucgui/Widget/LISTBOX_ScrollStep.o \
./application/ucgui/Widget/LISTBOX_SetAutoScroll.o \
./application/ucgui/Widget/LISTBOX_SetBkColor.o \
./application/ucgui/Widget/LISTBOX_SetOwner.o \
./application/ucgui/Widget/LISTBOX_SetOwnerDraw.o \
./application/ucgui/Widget/LISTBOX_SetScrollbarWidth.o \
./application/ucgui/Widget/LISTBOX_SetString.o \
./application/ucgui/Widget/LISTBOX_SetTextColor.o \
./application/ucgui/Widget/LISTVIEW.o \
./application/ucgui/Widget/LISTVIEW_Create.o \
./application/ucgui/Widget/LISTVIEW_CreateIndirect.o \
./application/ucgui/Widget/LISTVIEW_Default.o \
./application/ucgui/Widget/LISTVIEW_DeleteColumn.o \
./application/ucgui/Widget/LISTVIEW_DeleteRow.o \
./application/ucgui/Widget/LISTVIEW_GetBkColor.o \
./application/ucgui/Widget/LISTVIEW_GetFont.o \
./application/ucgui/Widget/LISTVIEW_GetHeader.o \
./application/ucgui/Widget/LISTVIEW_GetNumColumns.o \
./application/ucgui/Widget/LISTVIEW_GetNumRows.o \
./application/ucgui/Widget/LISTVIEW_GetSel.o \
./application/ucgui/Widget/LISTVIEW_GetTextColor.o \
./application/ucgui/Widget/LISTVIEW_SetBkColor.o \
./application/ucgui/Widget/LISTVIEW_SetColumnWidth.o \
./application/ucgui/Widget/LISTVIEW_SetFont.o \
./application/ucgui/Widget/LISTVIEW_SetGridVis.o \
./application/ucgui/Widget/LISTVIEW_SetItemColor.o \
./application/ucgui/Widget/LISTVIEW_SetItemText.o \
./application/ucgui/Widget/LISTVIEW_SetLBorder.o \
./application/ucgui/Widget/LISTVIEW_SetRBorder.o \
./application/ucgui/Widget/LISTVIEW_SetRowHeight.o \
./application/ucgui/Widget/LISTVIEW_SetSel.o \
./application/ucgui/Widget/LISTVIEW_SetTextAlign.o \
./application/ucgui/Widget/LISTVIEW_SetTextColor.o \
./application/ucgui/Widget/MENU.o \
./application/ucgui/Widget/MENU_Attach.o \
./application/ucgui/Widget/MENU_CreateIndirect.o \
./application/ucgui/Widget/MENU_Default.o \
./application/ucgui/Widget/MENU_DeleteItem.o \
./application/ucgui/Widget/MENU_DisableItem.o \
./application/ucgui/Widget/MENU_EnableItem.o \
./application/ucgui/Widget/MENU_GetItem.o \
./application/ucgui/Widget/MENU_GetItemText.o \
./application/ucgui/Widget/MENU_GetNumItems.o \
./application/ucgui/Widget/MENU_InsertItem.o \
./application/ucgui/Widget/MENU_Popup.o \
./application/ucgui/Widget/MENU_SetBkColor.o \
./application/ucgui/Widget/MENU_SetBorderSize.o \
./application/ucgui/Widget/MENU_SetFont.o \
./application/ucgui/Widget/MENU_SetItem.o \
./application/ucgui/Widget/MENU_SetTextColor.o \
./application/ucgui/Widget/MENU__FindItem.o \
./application/ucgui/Widget/MESSAGEBOX.o \
./application/ucgui/Widget/MULTIEDIT.o \
./application/ucgui/Widget/MULTIEDIT_Create.o \
./application/ucgui/Widget/MULTIEDIT_CreateIndirect.o \
./application/ucgui/Widget/MULTIPAGE.o \
./application/ucgui/Widget/MULTIPAGE_Create.o \
./application/ucgui/Widget/MULTIPAGE_CreateIndirect.o \
./application/ucgui/Widget/MULTIPAGE_Default.o \
./application/ucgui/Widget/PROGBAR.o \
./application/ucgui/Widget/PROGBAR_Create.o \
./application/ucgui/Widget/PROGBAR_CreateIndirect.o \
./application/ucgui/Widget/RADIO.o \
./application/ucgui/Widget/RADIO_Create.o \
./application/ucgui/Widget/RADIO_CreateIndirect.o \
./application/ucgui/Widget/RADIO_Default.o \
./application/ucgui/Widget/RADIO_Image.o \
./application/ucgui/Widget/RADIO_SetBkColor.o \
./application/ucgui/Widget/RADIO_SetDefaultImage.o \
./application/ucgui/Widget/RADIO_SetFont.o \
./application/ucgui/Widget/RADIO_SetGroupId.o \
./application/ucgui/Widget/RADIO_SetImage.o \
./application/ucgui/Widget/RADIO_SetText.o \
./application/ucgui/Widget/RADIO_SetTextColor.o \
./application/ucgui/Widget/SCROLLBAR.o \
./application/ucgui/Widget/SCROLLBAR_Create.o \
./application/ucgui/Widget/SCROLLBAR_CreateIndirect.o \
./application/ucgui/Widget/SCROLLBAR_Defaults.o \
./application/ucgui/Widget/SCROLLBAR_GetValue.o \
./application/ucgui/Widget/SCROLLBAR_SetWidth.o \
./application/ucgui/Widget/SLIDER.o \
./application/ucgui/Widget/SLIDER_Create.o \
./application/ucgui/Widget/SLIDER_CreateIndirect.o \
./application/ucgui/Widget/TEXT.o \
./application/ucgui/Widget/TEXT_Create.o \
./application/ucgui/Widget/TEXT_CreateIndirect.o \
./application/ucgui/Widget/TEXT_SetBkColor.o \
./application/ucgui/Widget/TEXT_SetFont.o \
./application/ucgui/Widget/TEXT_SetText.o \
./application/ucgui/Widget/TEXT_SetTextAlign.o \
./application/ucgui/Widget/TEXT_SetTextColor.o \
./application/ucgui/Widget/WIDGET.o \
./application/ucgui/Widget/WIDGET_Effect_3D.o \
./application/ucgui/Widget/WIDGET_Effect_3D1L.o \
./application/ucgui/Widget/WIDGET_Effect_3D2L.o \
./application/ucgui/Widget/WIDGET_Effect_None.o \
./application/ucgui/Widget/WIDGET_Effect_Simple.o \
./application/ucgui/Widget/WIDGET_FillStringInRect.o \
./application/ucgui/Widget/WIDGET_SetEffect.o \
./application/ucgui/Widget/WIDGET_SetWidth.o \
./application/ucgui/Widget/WINDOW.o \
./application/ucgui/Widget/WINDOW_Default.o 

C_DEPS += \
./application/ucgui/Widget/BUTTON.d \
./application/ucgui/Widget/BUTTON_BMP.d \
./application/ucgui/Widget/BUTTON_Bitmap.d \
./application/ucgui/Widget/BUTTON_Create.d \
./application/ucgui/Widget/BUTTON_CreateIndirect.d \
./application/ucgui/Widget/BUTTON_Default.d \
./application/ucgui/Widget/BUTTON_Get.d \
./application/ucgui/Widget/BUTTON_IsPressed.d \
./application/ucgui/Widget/BUTTON_SelfDraw.d \
./application/ucgui/Widget/BUTTON_SetTextAlign.d \
./application/ucgui/Widget/BUTTON_StreamedBitmap.d \
./application/ucgui/Widget/BUTTON__SetBitmapObj.d \
./application/ucgui/Widget/CHECKBOX.d \
./application/ucgui/Widget/CHECKBOX_Create.d \
./application/ucgui/Widget/CHECKBOX_CreateIndirect.d \
./application/ucgui/Widget/CHECKBOX_Default.d \
./application/ucgui/Widget/CHECKBOX_GetState.d \
./application/ucgui/Widget/CHECKBOX_Image.d \
./application/ucgui/Widget/CHECKBOX_IsChecked.d \
./application/ucgui/Widget/CHECKBOX_SetBkColor.d \
./application/ucgui/Widget/CHECKBOX_SetDefaultImage.d \
./application/ucgui/Widget/CHECKBOX_SetFont.d \
./application/ucgui/Widget/CHECKBOX_SetImage.d \
./application/ucgui/Widget/CHECKBOX_SetNumStates.d \
./application/ucgui/Widget/CHECKBOX_SetSpacing.d \
./application/ucgui/Widget/CHECKBOX_SetState.d \
./application/ucgui/Widget/CHECKBOX_SetText.d \
./application/ucgui/Widget/CHECKBOX_SetTextAlign.d \
./application/ucgui/Widget/CHECKBOX_SetTextColor.d \
./application/ucgui/Widget/DIALOG.d \
./application/ucgui/Widget/DROPDOWN.d \
./application/ucgui/Widget/DROPDOWN_Create.d \
./application/ucgui/Widget/DROPDOWN_CreateIndirect.d \
./application/ucgui/Widget/DROPDOWN_DeleteItem.d \
./application/ucgui/Widget/DROPDOWN_InsertString.d \
./application/ucgui/Widget/DROPDOWN_ItemSpacing.d \
./application/ucgui/Widget/DROPDOWN_SetAutoScroll.d \
./application/ucgui/Widget/DROPDOWN_SetTextAlign.d \
./application/ucgui/Widget/DROPDOWN_SetTextHeight.d \
./application/ucgui/Widget/EDIT.d \
./application/ucgui/Widget/EDITBin.d \
./application/ucgui/Widget/EDITDec.d \
./application/ucgui/Widget/EDITFloat.d \
./application/ucgui/Widget/EDITHex.d \
./application/ucgui/Widget/EDIT_Create.d \
./application/ucgui/Widget/EDIT_CreateIndirect.d \
./application/ucgui/Widget/EDIT_Default.d \
./application/ucgui/Widget/EDIT_GetNumChars.d \
./application/ucgui/Widget/EDIT_SetCursorAtChar.d \
./application/ucgui/Widget/EDIT_SetInsertMode.d \
./application/ucgui/Widget/EDIT_SetSel.d \
./application/ucgui/Widget/EDIT_SetpfAddKeyEx.d \
./application/ucgui/Widget/EDIT_SetpfUpdateBuffer.d \
./application/ucgui/Widget/FRAMEWIN.d \
./application/ucgui/Widget/FRAMEWIN_AddMenu.d \
./application/ucgui/Widget/FRAMEWIN_Button.d \
./application/ucgui/Widget/FRAMEWIN_ButtonClose.d \
./application/ucgui/Widget/FRAMEWIN_ButtonMax.d \
./application/ucgui/Widget/FRAMEWIN_ButtonMin.d \
./application/ucgui/Widget/FRAMEWIN_Create.d \
./application/ucgui/Widget/FRAMEWIN_CreateIndirect.d \
./application/ucgui/Widget/FRAMEWIN_Default.d \
./application/ucgui/Widget/FRAMEWIN_Get.d \
./application/ucgui/Widget/FRAMEWIN_IsMinMax.d \
./application/ucgui/Widget/FRAMEWIN_MinMaxRest.d \
./application/ucgui/Widget/FRAMEWIN_SetBorderSize.d \
./application/ucgui/Widget/FRAMEWIN_SetColors.d \
./application/ucgui/Widget/FRAMEWIN_SetFont.d \
./application/ucgui/Widget/FRAMEWIN_SetResizeable.d \
./application/ucgui/Widget/FRAMEWIN_SetTitleHeight.d \
./application/ucgui/Widget/FRAMEWIN_SetTitleVis.d \
./application/ucgui/Widget/FRAMEWIN__UpdateButtons.d \
./application/ucgui/Widget/GUI_ARRAY.d \
./application/ucgui/Widget/GUI_ARRAY_DeleteItem.d \
./application/ucgui/Widget/GUI_ARRAY_InsertItem.d \
./application/ucgui/Widget/GUI_ARRAY_ResizeItem.d \
./application/ucgui/Widget/GUI_DRAW.d \
./application/ucgui/Widget/GUI_DRAW_BITMAP.d \
./application/ucgui/Widget/GUI_DRAW_BMP.d \
./application/ucgui/Widget/GUI_DRAW_STREAMED.d \
./application/ucgui/Widget/GUI_DRAW_Self.d \
./application/ucgui/Widget/GUI_EditBin.d \
./application/ucgui/Widget/GUI_EditDec.d \
./application/ucgui/Widget/GUI_EditFloat.d \
./application/ucgui/Widget/GUI_EditHex.d \
./application/ucgui/Widget/GUI_EditString.d \
./application/ucgui/Widget/GUI_HOOK.d \
./application/ucgui/Widget/HEADER.d \
./application/ucgui/Widget/HEADER_BMP.d \
./application/ucgui/Widget/HEADER_Bitmap.d \
./application/ucgui/Widget/HEADER_Create.d \
./application/ucgui/Widget/HEADER_CreateIndirect.d \
./application/ucgui/Widget/HEADER_StreamedBitmap.d \
./application/ucgui/Widget/HEADER__SetDrawObj.d \
./application/ucgui/Widget/LISTBOX.d \
./application/ucgui/Widget/LISTBOX_Create.d \
./application/ucgui/Widget/LISTBOX_CreateIndirect.d \
./application/ucgui/Widget/LISTBOX_Default.d \
./application/ucgui/Widget/LISTBOX_DeleteItem.d \
./application/ucgui/Widget/LISTBOX_Font.d \
./application/ucgui/Widget/LISTBOX_GetItemText.d \
./application/ucgui/Widget/LISTBOX_GetNumItems.d \
./application/ucgui/Widget/LISTBOX_InsertString.d \
./application/ucgui/Widget/LISTBOX_ItemDisabled.d \
./application/ucgui/Widget/LISTBOX_ItemSpacing.d \
./application/ucgui/Widget/LISTBOX_MultiSel.d \
./application/ucgui/Widget/LISTBOX_ScrollStep.d \
./application/ucgui/Widget/LISTBOX_SetAutoScroll.d \
./application/ucgui/Widget/LISTBOX_SetBkColor.d \
./application/ucgui/Widget/LISTBOX_SetOwner.d \
./application/ucgui/Widget/LISTBOX_SetOwnerDraw.d \
./application/ucgui/Widget/LISTBOX_SetScrollbarWidth.d \
./application/ucgui/Widget/LISTBOX_SetString.d \
./application/ucgui/Widget/LISTBOX_SetTextColor.d \
./application/ucgui/Widget/LISTVIEW.d \
./application/ucgui/Widget/LISTVIEW_Create.d \
./application/ucgui/Widget/LISTVIEW_CreateIndirect.d \
./application/ucgui/Widget/LISTVIEW_Default.d \
./application/ucgui/Widget/LISTVIEW_DeleteColumn.d \
./application/ucgui/Widget/LISTVIEW_DeleteRow.d \
./application/ucgui/Widget/LISTVIEW_GetBkColor.d \
./application/ucgui/Widget/LISTVIEW_GetFont.d \
./application/ucgui/Widget/LISTVIEW_GetHeader.d \
./application/ucgui/Widget/LISTVIEW_GetNumColumns.d \
./application/ucgui/Widget/LISTVIEW_GetNumRows.d \
./application/ucgui/Widget/LISTVIEW_GetSel.d \
./application/ucgui/Widget/LISTVIEW_GetTextColor.d \
./application/ucgui/Widget/LISTVIEW_SetBkColor.d \
./application/ucgui/Widget/LISTVIEW_SetColumnWidth.d \
./application/ucgui/Widget/LISTVIEW_SetFont.d \
./application/ucgui/Widget/LISTVIEW_SetGridVis.d \
./application/ucgui/Widget/LISTVIEW_SetItemColor.d \
./application/ucgui/Widget/LISTVIEW_SetItemText.d \
./application/ucgui/Widget/LISTVIEW_SetLBorder.d \
./application/ucgui/Widget/LISTVIEW_SetRBorder.d \
./application/ucgui/Widget/LISTVIEW_SetRowHeight.d \
./application/ucgui/Widget/LISTVIEW_SetSel.d \
./application/ucgui/Widget/LISTVIEW_SetTextAlign.d \
./application/ucgui/Widget/LISTVIEW_SetTextColor.d \
./application/ucgui/Widget/MENU.d \
./application/ucgui/Widget/MENU_Attach.d \
./application/ucgui/Widget/MENU_CreateIndirect.d \
./application/ucgui/Widget/MENU_Default.d \
./application/ucgui/Widget/MENU_DeleteItem.d \
./application/ucgui/Widget/MENU_DisableItem.d \
./application/ucgui/Widget/MENU_EnableItem.d \
./application/ucgui/Widget/MENU_GetItem.d \
./application/ucgui/Widget/MENU_GetItemText.d \
./application/ucgui/Widget/MENU_GetNumItems.d \
./application/ucgui/Widget/MENU_InsertItem.d \
./application/ucgui/Widget/MENU_Popup.d \
./application/ucgui/Widget/MENU_SetBkColor.d \
./application/ucgui/Widget/MENU_SetBorderSize.d \
./application/ucgui/Widget/MENU_SetFont.d \
./application/ucgui/Widget/MENU_SetItem.d \
./application/ucgui/Widget/MENU_SetTextColor.d \
./application/ucgui/Widget/MENU__FindItem.d \
./application/ucgui/Widget/MESSAGEBOX.d \
./application/ucgui/Widget/MULTIEDIT.d \
./application/ucgui/Widget/MULTIEDIT_Create.d \
./application/ucgui/Widget/MULTIEDIT_CreateIndirect.d \
./application/ucgui/Widget/MULTIPAGE.d \
./application/ucgui/Widget/MULTIPAGE_Create.d \
./application/ucgui/Widget/MULTIPAGE_CreateIndirect.d \
./application/ucgui/Widget/MULTIPAGE_Default.d \
./application/ucgui/Widget/PROGBAR.d \
./application/ucgui/Widget/PROGBAR_Create.d \
./application/ucgui/Widget/PROGBAR_CreateIndirect.d \
./application/ucgui/Widget/RADIO.d \
./application/ucgui/Widget/RADIO_Create.d \
./application/ucgui/Widget/RADIO_CreateIndirect.d \
./application/ucgui/Widget/RADIO_Default.d \
./application/ucgui/Widget/RADIO_Image.d \
./application/ucgui/Widget/RADIO_SetBkColor.d \
./application/ucgui/Widget/RADIO_SetDefaultImage.d \
./application/ucgui/Widget/RADIO_SetFont.d \
./application/ucgui/Widget/RADIO_SetGroupId.d \
./application/ucgui/Widget/RADIO_SetImage.d \
./application/ucgui/Widget/RADIO_SetText.d \
./application/ucgui/Widget/RADIO_SetTextColor.d \
./application/ucgui/Widget/SCROLLBAR.d \
./application/ucgui/Widget/SCROLLBAR_Create.d \
./application/ucgui/Widget/SCROLLBAR_CreateIndirect.d \
./application/ucgui/Widget/SCROLLBAR_Defaults.d \
./application/ucgui/Widget/SCROLLBAR_GetValue.d \
./application/ucgui/Widget/SCROLLBAR_SetWidth.d \
./application/ucgui/Widget/SLIDER.d \
./application/ucgui/Widget/SLIDER_Create.d \
./application/ucgui/Widget/SLIDER_CreateIndirect.d \
./application/ucgui/Widget/TEXT.d \
./application/ucgui/Widget/TEXT_Create.d \
./application/ucgui/Widget/TEXT_CreateIndirect.d \
./application/ucgui/Widget/TEXT_SetBkColor.d \
./application/ucgui/Widget/TEXT_SetFont.d \
./application/ucgui/Widget/TEXT_SetText.d \
./application/ucgui/Widget/TEXT_SetTextAlign.d \
./application/ucgui/Widget/TEXT_SetTextColor.d \
./application/ucgui/Widget/WIDGET.d \
./application/ucgui/Widget/WIDGET_Effect_3D.d \
./application/ucgui/Widget/WIDGET_Effect_3D1L.d \
./application/ucgui/Widget/WIDGET_Effect_3D2L.d \
./application/ucgui/Widget/WIDGET_Effect_None.d \
./application/ucgui/Widget/WIDGET_Effect_Simple.d \
./application/ucgui/Widget/WIDGET_FillStringInRect.d \
./application/ucgui/Widget/WIDGET_SetEffect.d \
./application/ucgui/Widget/WIDGET_SetWidth.d \
./application/ucgui/Widget/WINDOW.d \
./application/ucgui/Widget/WINDOW_Default.d 


# Each subdirectory must supply rules for building sources it contributes
application/ucgui/Widget/%.o: ../application/ucgui/Widget/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imac -mabi=ilp32 -mcmodel=medany -mno-save-restore -O0 -ffunction-sections -fdata-sections -fno-common  -g -DDOWNLOAD_MODE=DOWNLOAD_MODE_FLASHXIP -I"D:\risc_studio\456\nuclei_sdk\NMSIS\DSP\Include" -I"D:\risc_studio\456\nuclei_sdk\NMSIS\NN\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Board\gd32vf103v_rvstar\Include" -I"D:\risc_studio\456\application" -I"D:\risc_studio\456\nuclei_sdk\NMSIS\Core\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Common\Include" -I"D:\risc_studio\456\nuclei_sdk\SoC\gd32vf103\Common\Include\Usb" -I"D:\risc_studio\456\application\ucgui" -I"D:\risc_studio\456\application\ucgui\WM" -I"D:\risc_studio\456\application\ucgui\ConvertColor" -I"D:\risc_studio\456\application\ucgui\ConvertMono" -I"D:\risc_studio\456\application\ucgui\Core" -I"D:\risc_studio\456\application\ucgui\Font" -I"D:\risc_studio\456\application\ucgui\JPEG" -I"D:\risc_studio\456\application\ucgui\LCDDriver" -I"D:\risc_studio\456\application\ucgui\MemDev" -I"D:\risc_studio\456\application\ucgui\MultiLayer" -I"D:\risc_studio\456\application\ucgui\Widget" -I"D:\risc_studio\456\application\gui_config" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


